### PR TITLE
WiFi Adapter

### PR DESCRIPTION
**Pull request by ArkadiuszRaj**
Using ESP-12F module (supporting RRF DWC)

When DC buck converter will not be moved to back side, then this add on will be postioned over it.
No idea however if the vertical spacing would be OK.

Using two header sockets, no additional mounting  screws are necessary. 
ESP-12F to be soldered by hand. Same for headers sockets. The rest by JLCPCB (however I have not updated schematics fields with their product numbers)

Open questions:
- add some LEDs? on the top layer meaning to be soldered by hand as well (as JLCPCB does single side PCBA only)
- is the distance between headers correct? must be double / tripple checked

### CODE REVIEW

**Comment by ArkadiuszRaj** [comment]
PCB edited with KiCad nightly build of Jan 17th.

**Comment by ghent360** [comment]
Sorry I don't have a lot of experience with ESP modules:
If you assume the ~CS and BOOT are floating at reset, does it need pull up/down resistors on GPIO0 and GPIO15 to boot in UART mode (I assume that is the desired state)?

Does the RST need R/C to reset at power up or the module already has these internally?

There is quite a collection of resistor values on the EXP1 and EXP2 pin are these calculated with something specific in mind? If so it would be good to add a comment in the schematics, why the values are what they are.

**Comment by ghent360** [comment]
I see the resistor values are coming from https://github.com/gloomyandy/RepRapFirmware/wiki/SKR-Wifi most likely.

**Comment by ghent360** [comment]
I noticed you are shorting the Reset and Wakeup. We  should probably put that as a solder jumper, so the short can be removed if need be. Also add a jumper (on the bottom so it faces up) between  the EXP1 pin 10  and the 5V power, you don't want to try and power the whole board from the USB connector on the add-on. It could be solder jumper as well.

**Comment by ArkadiuszRaj** [comment]
Morning,

Yes. RRF puts some requirements on the Wi-Fi adapter. This is why simple
ESP-01s will not work.

In principle I was basing on the ESP data sheets together with RRF hack.
There can be still minor issues like aforementioned CS line. USB connection
is taken from SKR RRF Wi-Fi board that I have connected to my SKR 1.4 and
is working fine. Resistors values in this SKR adapter follows RRF
requirements as well.

The way how RRF works with WI-FI (to my understanding) is to schedule reset
by dedicated Pin. Thus no floating state shall be expected.
But pull-up can be added.

Selected CH340 is extended part at JLCPCB, the basic one is larger (soic16)
and needs external crystal. So +3€ as for now.

BTW. For my projects I have created python script that takes kicad’s bom
and pos files and creates needed data for JLC PCBA as well as bom ordering
files for Mouser and TME. It requires additional fields in the schematics,
like “mechanical”, “rotation” etc.

W dniu niedz., 17.01.2021 o 11:01 ghent360 <notifications@github.com>
napisał(a):

**Comment by ghent360** [comment]
I think the EXP1 and EXP2 connectors are flipped. You need to flip the board in order to connect to the PrntrBoard and then the EXP1 would be on the left and EXP2 on the right, which would not be correct (the ESP antenna facing right)

**Comment by ArkadiuszRaj** [comment]
Wakeup is shorted to automatically boot ESP.
Jumpers are a good idea, especially for USB connector. BTW, RRF can update
ESP FW by itself, as UART is connected to CPU.
Here ESP UART is connected to USB...

niedz., 17 sty 2021 o 11:16 ghent360 <notifications@github.com> napisał(a):

**Comment by ghent360** [comment]
Distance between the connectors should be 21.3868mm (I know it's an odd number, I didn't pan it).

**Comment by ArkadiuszRaj** [comment]
Pushed update. It is about proper layer and spacing for headers.
Plus power source selector.


niedz., 17 sty 2021 o 11:43 ghent360 <notifications@github.com> napisał(a):

**Comment by ghent360** [comment]
The Add-on looks good, thank you for your contributions.
However I think the previous PR has some issues with the main board, that we need to fix:

The sd-card has no CS pin connected, I don't believe it would work without one. Also there is nothing connected to pin 4 on the EXT2 connector. We have PD2 as spare (SDIO_CMD) - we can use it to drive CS on the sd-card. We don't have to use dedicated SPI for the sd-card. I think it can share the lines with SPI1, so we have 3 extra pins.

It would probably be best to connect one of the extra pins to pin 7 of EXT2. Currently it is shared with the sd_detect pin on the sd-card socket.

**Comment by ArkadiuszRaj** [comment]
Added some more info to make schematics easier to understand.
Pins on EXT1/2 can be used freely as those must be defined in RRF config.

In the essence, to comply with RRF, this adapter must expose:
- SPI with CS signal,
- Data ready output (from ESP),
- Transfer ready input (to ESP),
- Reset line.

excerpt from board.txt
```
//ESP Settings
8266wifi.espDataReadyPin = A.15;
8266wifi.lpcTfrReadyPin = C.11;
8266wifi.espResetPin = B.10;
//ESP RX/TX Settings
8266wifi.serialRxTxPins = { PC7, PC6 } ;
serial.aux.rxTxPins = {NoPin, NoPin};
```


BTW, if SD card will not use hardware SPI, then I guess it would be problematic to update firmware. I.e. IAP bootloader  uses SPI/SDIO to access SD card content.

**Comment by ghent360** [comment]
I think I understand the ESP interface.

The issue is that on the PrntrBoard EXP2.4 (RST) is not connected - there is no trace to that pin in my original design. In the "reprap" screens that pin is usually used to detect if SD-card is inserted in the LCD sd-card slot. This is optional feature that I skipped because I was running out of pins.

Does this make sense?

**Pull request merged**
